### index dishes
GET http://localhost:3000/dishes.json

### show dish
GET http://localhost:3000/dishes/3.json

### create dish
POST http://localhost:3000/dishes.json
content-type: application/json

{
  "name": "Test",
  "description": "test",
  "buy_again": "Yes",
  "restaurant": "test",
  "image": "image test"
}

### update dish
PATCH http://localhost:3000/dishes/3.json
content-type: application/json

{
  "description": "Normal order: no sprouts, with creamy teriyaki dressing, shredded carrots, brown rice, and sweet chilli chicken."
}

### delete dish
DELETE http://localhost:3000/dishes/5.json


#------ User Signup & Login ------#

###
POST http://localhost:3000/users.json
content-type: application/json

{
  "name": "Frodo Baggins",
  "email": "frodo@theonering.com",
  "password": "password",
  "password_confirmation": "password"
}